# Generated by Django 4.1.7 on 2023-04-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_file', models.FileField(upload_to='Songs/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name_plural': 'Music DataBase',
            },
        ),
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_sheet', models.FileField(upload_to='Songs/<django.db.models.fields.CharField>')),
                ('midi_file', models.FileField(upload_to='Songs/<django.db.models.fields.CharField>')),
                ('choreo_file', models.FileField(upload_to='Songs/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name_plural': 'Music DataBase',
            },
        ),
    ]
