# Generated by Django 4.1.7 on 2023-04-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Media permissions',
                'permissions': (('AddMedia', 'AddMedia'), ('DeleteMedia', 'DeleteMedia'), ('ManageMedia', 'ManageMedia')),
            },
        ),
        migrations.CreateModel(
            name='music_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Music permissions',
                'permissions': (('AddSong', 'AddSong'), ('DeleteSong', 'DeleteSong'), ('ManageSong', 'ManageSong')),
            },
        ),
        migrations.CreateModel(
            name='user_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'User permissions',
                'permissions': (('Admin', 'Admin'), ('SettingsManager', 'SettingsManager'), ('AddUser', 'AddUser'), ('DeleteUser', 'DeleteUser'), ('ManageUser', 'ManageUser')),
            },
        ),
    ]
