# Generated by Django 4.1.7 on 2023-04-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'All songs',
            },
        ),
        migrations.CreateModel(
            name='song_mediafiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('main_item', models.BooleanField()),
                ('song_file', models.FileField(upload_to='Songs/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name_plural': "Media (foto's and video's)",
            },
        ),
        migrations.CreateModel(
            name='song_otherfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_file', models.FileField(upload_to='Songs/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name_plural': 'Other song files',
            },
        ),
        migrations.CreateModel(
            name='song_sheetfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('main_item', models.BooleanField()),
                ('song_file', models.FileField(upload_to='Songs/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name_plural': 'Sheets',
            },
        ),
        migrations.CreateModel(
            name='song_soundfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('main_item', models.BooleanField()),
                ('song_file', models.FileField(upload_to='Songs/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name_plural': 'Media (sounds & mp3)',
            },
        ),
    ]
