# Generated by Django 4.1.7 on 2023-04-24 12:51

import Songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0002_song_list_page_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_list',
            name='guest_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song_mediafiles',
            name='song_file',
            field=models.FileField(upload_to=Songs.models.song_file_path),
        ),
        migrations.AlterField(
            model_name='song_otherfiles',
            name='song_file',
            field=models.FileField(upload_to=Songs.models.song_file_path),
        ),
        migrations.AlterField(
            model_name='song_sheetfiles',
            name='song_file',
            field=models.FileField(upload_to=Songs.models.song_file_path),
        ),
        migrations.AlterField(
            model_name='song_soundfiles',
            name='song_file',
            field=models.FileField(upload_to=Songs.models.song_file_path),
        ),
    ]
