# Generated by Django 4.1.7 on 2023-05-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0004_rename_guest_active_song_list_guestactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song_list',
            old_name='guestactive',
            new_name='guest_active',
        ),
        migrations.RenameField(
            model_name='song_list',
            old_name='pagetopic',
            new_name='page_topic',
        ),
        migrations.RenameField(
            model_name='song_list',
            old_name='songname',
            new_name='song_name',
        ),
    ]
