# Generated by Django 4.1.7 on 2023-05-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0005_rename_guestactive_song_list_guest_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_list',
            name='page_topic',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('archive', 'archive'), ('folder', 'folder')], default='active', max_length=200),
        ),
    ]
