# Generated by Django 4.1.7 on 2023-05-16 13:16

import Songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0006_alter_song_list_page_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='song_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('foto', 'foto')], default='active', max_length=200)),
                ('song_file', models.FileField(upload_to=Songs.models.song_file_path)),
            ],
            options={
                'verbose_name_plural': 'Song files',
            },
        ),
        migrations.DeleteModel(
            name='song_mediafiles',
        ),
        migrations.DeleteModel(
            name='song_otherfiles',
        ),
        migrations.DeleteModel(
            name='song_sheetfiles',
        ),
        migrations.DeleteModel(
            name='song_soundfiles',
        ),
    ]
